DEFAULT_PAGE_SIZE = 25
MAX_PAGE_SIZE = 100

ROLE_ADMIN = "ADMIN"
ROLE_MANAGER = "MANAGER"
ROLE_USER = "USER"

SESSION_STATUS_ACTIVE = "active"
SESSION_STATUS_PENDING = "pending"
SESSION_STATUS_CLOSED = "closed"
SESSION_STATUS_ERROR = "error"

DISPLAY_MODE_FULL_DESKTOP = "full_desktop"
DISPLAY_MODE_REMOTE_APP = "remote_app"
DISPLAY_MODE_SEAMLESS = "seamless"
DISPLAY_MODE_HTML5 = "html5"
